services:
  decimer_api:
    image: docker.io/docminus/decimer_api:latest # for dockerhub image
    # image: decimer_api:latest  # for locally built image
    container_name: decimerapi
    ports:
      - "8099:8099"
    volumes:
      - model_files:/home/appuser/.data/DECIMER-V2 # this is the path to the DECIMER-V2 data directory
    restart: always

volumes:
  model_files:
