services:
  decimer_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: decimer_api:latest
    networks:
      - decimernetwork

networks:
  decimernetwork:
    name: decimernetwork
